### ISSUE TITLE
small enhancement requests

### ISSUE THREAD

**Issue by rcrooks** [blaqbern/eclectic-syntax#2]
@blaqbern thanks for the answer on the font :)

I did have a couple of small requests: a little more contrast for:
- indent guides
- comments (I work on APIDOC and JSDOC stuff a lot, plus try to comment all code thoroughly)
- selections

If you're not inclined, I'll just fork this and make my own version. Really like the color scheme.

**Comment by blaqbern** [comment]
Please feel free to fork if you like.

I'm willing to consider these changes, but I prefer to keep:
- invisibles _darker_ than the background
- comments at least somewhat muted (just a matter of taste). It may be possible to style JSDOC comments differently as well since they start with `/**`. In this case, I'd be open to whatever color. 
- I didn't put too much time into the choice of selection color, so I'm definitely open to suggestions on that score. I'd like to change the foreground color on selected text too, but I haven't figured out how to do that.

Thanks for checking out the theme.

**Comment by rcrooks** [comment]
Thanks for considering. I’ll probably fork and modify when I find the time. On comments, yes, the JSDOC ones are the ones I mostly care about. I’ve noticed that some themes manage to highlight @param, etc., though I haven’t figured out yet how that’s done. Robert

Robert Crooks Director of Learning Services Brightcove, Inc
On Mon, Mar 21, 2016 at 10:11 PM, Chris Blackburn notifications@github.com wrote:
Please feel free to fork if you like.

I'm willing to consider these changes, but I prefer to keep:
- invisibles darker than the background
- comments at least somewhat muted (just a matter of taste). It may be possible to style JSDOC comments differently as well since they start with /*\* . In this case, I'd be open to whatever color.
- I didn't put too much time into the choice of selection color, so I'm definitely open to suggestions on that score. I'd like to change the foreground color on selected text too, but I haven't figured out how to do that.

Thanks for checking out the theme.

**Comment by blaqbern** [comment]
Awesome. I look forward to checking it out.
I'll leave this open for now, and if I get a free second, I'll look into changing JSDOC comments, and what that entails exactly. I'll let you know what I find.

**Comment by blaqbern** [comment]
649bca2 gives JSDOC-style comments higher contrast. This update will be reflected in version 0.2.0 on apm.

**Comment by rcrooks** [comment]
Cool! Look forward to trying it out. :)

Robert Crooks Director of Learning Services Brightcove, Inc
On Fri, Mar 25, 2016 at 11:47 PM, Chris Blackburn notifications@github.com wrote:
649bca2 [https://github.com/blaqbern/eclectic-syntax/commit/649bca240f135d0120cbcbb3e4d052fb5f551314] gives JSDOC-style comments higher contrast. This update will be reflected in version 0.2.0 on apm.

**Comment by rcrooks** [comment]
Excellent!

Robert Crooks Director of Learning Services Brightcove, Inc
On Sat, Mar 26, 2016 at 12:00 PM, Robert Crooks rcrooks@brightcove.com wrote:
Cool! Look forward to trying it out. :)

Robert Crooks Director of Learning Services Brightcove, Inc
On Fri, Mar 25, 2016 at 11:47 PM, Chris Blackburn notifications@github.com wrote:
649bca2 [https://github.com/blaqbern/eclectic-syntax/commit/649bca240f135d0120cbcbb3e4d052fb5f551314] gives JSDOC-style comments higher contrast. This update will be reflected in version 0.2.0 on apm.
